### ISSUE TITLE
Play/Pause button styles do not match their actions

### ISSUE THREAD

**Issue by rmscode** [cwhitelam/Stretch-Timer#3]
When the app loads, a "pause" icon is presented by default in the timer controls. Clicking that button starts the timer and the style is then updated to display a "play" icon which will pause the timer when clicked.

**Comment by cwhitelam** [comment]
hello

**Comment by cwhitelam** [comment]
dfgh

**Comment by cwhitelam** [comment]
dfgh

**Comment by cwhitelam** [comment]
dfgh

**Comment by cwhitelam** [comment]
dfgh

**Comment by rmscode** [comment]
@cwhitelam ???

**Comment by cwhitelam** [comment]
@rmscode was testing a github feature for the ticketing system lol
